# Empirical billing of candidate operations at n = 1024 (flopscope 0.12.1). Units: FLOPs and "units" (1 unit = 2 n^3).
import warnings; warnings.filterwarnings("ignore")
import numpy as np, flopscope as flops, flopscope.numpy as fnp
flops.configure(symmetry_warnings=False)
n = 1024; U = 2*n**3
rng = np.random.default_rng(0)
A = fnp.asarray(rng.standard_normal((n, n)), dtype=fnp.float32); B = fnp.asarray(rng.standard_normal((n, n)), dtype=fnp.float32)
S = fnp.asarray((lambda x: x @ x.T)(rng.standard_normal((n, n))).astype(np.float32)); v = fnp.asarray(rng.standard_normal(n), dtype=fnp.float32)
A16 = A.astype(fnp.float16); A64 = A.astype(fnp.float64)
def bill(name, f):
    with flops.BudgetContext(flop_budget=2**50, quiet=True) as ctx:
        try: f(); c = ctx.flops_used; print(f"{name:58s} {c:>16,d}  {c/U:8.4f} units")
        except Exception as e: print(f"{name:58s} ERROR {type(e).__name__}: {str(e)[:80]}")
Ssym = None
with flops.BudgetContext(flop_budget=2**50, quiet=True): Ssym = flops.as_symmetric(S, symmetry=(0, 1))
out = fnp.empty((n, n), dtype=fnp.float32)
bill("matmul f32 A@B", lambda: A @ B)
bill("matmul f16", lambda: A16 @ A16)
bill("matmul f64", lambda: A64 @ A64)
bill("matmul out=", lambda: fnp.matmul(A, B, out=out))
bill("A @ A (same object)", lambda: A @ A)
bill("A @ A.T (Gram, same object)", lambda: A @ A.T)
bill("einsum ik,jk->ij (A,A) Gram", lambda: fnp.einsum("ik,jk->ij", A, A))
bill("einsum ij,ia,jb->ab (S plain, A, A)", lambda: fnp.einsum("ij,ia,jb->ab", S, A, A))
bill("einsum ij,ia,jb->ab (S symmetric-tagged, A, A)", lambda: fnp.einsum("ij,ia,jb->ab", Ssym, A, A))
bill("Ssym @ A", lambda: Ssym @ A)
bill("A.T @ (Ssym @ A) two matmuls", lambda: A.T @ (Ssym @ A))
bill("batched matmul (4,n,n)@(4,n,n)", lambda: fnp.matmul(fnp.reshape(fnp.concatenate([A]*4), (4, n, n)), fnp.reshape(fnp.concatenate([B]*4), (4, n, n))))
bill("matvec A@v", lambda: A @ v)
bill("multiply A*B", lambda: A * B)
bill("multiply out=", lambda: fnp.multiply(A, B, out=out))
bill("add A+B", lambda: A + B)
bill("outer(v,v)", lambda: fnp.outer(v, v))
bill("sum(A, axis=0)", lambda: fnp.sum(A, axis=0))
bill("einsum ij,ij->i (rowwise dot)", lambda: fnp.einsum("ij,ij->i", A, B))
bill("A[:512] slice (getitem)", lambda: A[:512])
bill("A.T (transpose)", lambda: A.T)
bill("reshape", lambda: fnp.reshape(A, (n*n,)))
bill("copy", lambda: A.copy())
bill("astype f32->f16", lambda: A.astype(fnp.float16))
bill("astype f64->f32", lambda: A64.astype(fnp.float32))
bill("fill_diagonal", lambda: fnp.fill_diagonal(A.copy(), 0.0))
bill("diag(A)", lambda: fnp.diag(A))
bill("as_symmetric(S)", lambda: flops.as_symmetric(S, symmetry=(0, 1)))
bill("stats.norm.cdf(v) f32", lambda: flops.stats.norm.cdf(v))
bill("stats.norm.pdf(v) f32", lambda: flops.stats.norm.pdf(v))
bill("exp(v)", lambda: fnp.exp(v))
bill("sqrt(v)", lambda: fnp.sqrt(v))
bill("maximum(A,0)", lambda: fnp.maximum(A, 0))
bill("where(A>0,A,0)", lambda: fnp.where(A > 0, A, 0))
bill("linalg.qr(A[:, :384])", lambda: fnp.linalg.qr(A[:, :384]))
bill("linalg.svd(A) full", lambda: fnp.linalg.svd(A))
bill("linalg.eigh(Ssym)", lambda: fnp.linalg.eigh(Ssym))
bill("linalg.cholesky(S+nI)", lambda: fnp.linalg.cholesky(S + n*fnp.eye(n, dtype=fnp.float32)))
bill("linalg.solve(S, A)", lambda: fnp.linalg.solve(S, A))
bill("linalg.inv(S)", lambda: fnp.linalg.inv(S))
bill("fft.rfft(A, axis=1)", lambda: fnp.fft.rfft(A, axis=1))
bill("random standard_normal (n,n)", lambda: fnp.random.default_rng(0).standard_normal((n, n)))
