"""Summarize every result JSON under results/ into results/summary.md (one row per run)."""
import glob, json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def fmt(x, f="%.4g"):
    return "-" if x is None else (f % x)


def rows():
    out = []
    for f in sorted(glob.glob(os.path.join(HERE, "results", "*", "*.json"))):
        d = json.load(open(f))
        if "setup_window_s" in d and "per_mlp" not in d:
            out.append(("setup", os.path.relpath(f, HERE), d))
            continue
        out.append(("run", os.path.relpath(f, HERE), d))
    return out


def main():
    lines = ["| file | mode | n | fails | C/B max | residual per MLP (s) | wall max (s) | peak RSS (MB) | final MSE | MSE − noise |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    setup = ["| file | setup window per spawn (s) | max |", "|---|---|---|"]
    for kind, f, d in rows():
        if kind == "setup":
            setup.append(f"| {f} | {', '.join('%.2f' % x for x in d['setup_window_s'])} | {d['max_s']:.2f} |")
            continue
        s = d.get("summary", {})
        per = d.get("per_mlp", [])
        if d.get("mode") == "client-server emulation":
            mode = "client/server"
            res = [r.get("residual_wall_time_s") for r in per]
            fails = s.get("n_errors", 0) + s.get("n_over_residual_cap", 0) + s.get("n_over_wall_cap", 0) + s.get("n_nonfinite", 0)
            rss = f"srv {d.get('peak_rss_mb_server')} / cli {d.get('peak_rss_mb_client')}"
        else:
            mode = "in-process " + ("subprocess" if "subprocess" in d.get("cmd", []) else "local")
            res = [r.get("residual_wall_time_s") for r in per]
            fails = s.get("n_failed_rows")
            rss = str(d.get("peak_rss_mb_worker"))
        lines.append("| %s | %s | %d | %s | %s | %s | %s | %s | %s | %s |" % (
            f, mode, len(per), fails, fmt(s.get("C_over_B_max"), "%.5f"),
            ", ".join("%.3f" % (r or 0) for r in res), fmt(s.get("wall_max_s"), "%.1f"), rss,
            fmt(s.get("final_layer_mse"), "%.4e"), fmt(s.get("final_mse_minus_noise"), "%.4e")))
    open(os.path.join(HERE, "results", "summary.md"), "w").write(
        "# All runs (generated by scripts/summarize.py)\n\n" + "\n".join(lines) + "\n\n## Setup window\n\n" + "\n".join(setup) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
