"""Wick/Mehler Gaussian-copula estimator (DESIGN.md section 2), numpy float64 prototype.

State per layer: marginal transport T_i(g) = m_i + s_i (a1 g + a2 He2(g) + a3 He3(g)) of each pre-activation,
and the latent correlation R (z_i = T_i(g_i), g ~ N(0, R)). Joint cumulants of a = ReLU(z) are generated by
Mehler / loopless-hafnian sums of per-neuron Hermite profiles; the fresh weights select the tree sectors.
"""
import math
import numpy as np
from numpy.polynomial import polynomial as P

K = 8          # Mehler truncation (edge multiplicity)
PQ = 3         # max edge multiplicity in path sectors


def he_power(dmax):
    """power-basis coefficients of probabilists' Hermite He_0..He_dmax: list of arrays."""
    H = [np.array([1.0]), np.array([0.0, 1.0])]
    for d in range(1, dmax):
        H.append(P.polysub(P.polymulx(H[d]), d * H[d - 1]))
    return H[:dmax + 1]


HE = he_power(K + 4)
FACT = np.array([math.factorial(d) for d in range(K + 8)], dtype=float)


def upper_moments(u, kmax):
    """M_k(u) = int_u^inf g^k phi(g) dg, k = 0..kmax (u may be +-inf)."""
    M = np.zeros(kmax + 1)
    if u == np.inf:
        return M
    if u == -np.inf:
        for k in range(kmax + 1):
            M[k] = 0.0 if k % 2 else (np.prod(np.arange(k - 1, 0, -2, dtype=float)) if k > 0 else 1.0)
        return M
    phi = math.exp(-0.5 * u * u) / math.sqrt(2 * math.pi)
    M[0] = 0.5 * math.erfc(u / math.sqrt(2))
    if kmax >= 1:
        M[1] = phi
    for k in range(2, kmax + 1):
        M[k] = u ** (k - 1) * phi + (k - 1) * M[k - 2]
    return M


def positive_intervals(c):
    """intervals of g where the polynomial c (power basis) is > 0."""
    c = np.trim_zeros(np.asarray(c, float), 'b')
    if len(c) <= 1:
        return [(-np.inf, np.inf)] if (len(c) and c[0] > 0) else []
    r = np.roots(c[::-1])
    r = np.sort(r[np.abs(r.imag) < 1e-9].real)
    pts = [-np.inf] + list(r) + [np.inf]
    out = []
    for lo, hi in zip(pts[:-1], pts[1:]):
        if lo == -np.inf and hi == np.inf:
            mid = 0.0
        elif lo == -np.inf:
            mid = hi - 1.0
        elif hi == np.inf:
            mid = lo + 1.0
        else:
            mid = 0.5 * (lo + hi)
        if P.polyval(mid, c) > 0:
            out.append((lo, hi))
    return out


def profiles(m, s, a, rmax=4, dmax=K):
    """Hermite profiles E[F^r He_d(g)] for F = ReLU(T(g)), r = 1..rmax, d = 0..dmax. returns (rmax, n, dmax+1)."""
    n = len(m)
    out = np.zeros((rmax, n, dmax + 1))
    for i in range(n):
        T = np.array([m[i] - s[i] * a[i, 1], s[i] * (a[i, 0] - 3 * a[i, 2]), s[i] * a[i, 1], s[i] * a[i, 2]])
        ivs = positive_intervals(T)
        kmax = 3 * rmax + dmax + 1
        Mint = np.zeros(kmax + 1)
        for lo, hi in ivs:
            Mint += upper_moments(lo, kmax) - upper_moments(hi, kmax)
        Tr = np.array([1.0])
        for r in range(rmax):
            Tr = P.polymul(Tr, T)
            for d in range(dmax + 1):
                c = P.polymul(Tr, HE[d])
                out[r, i, d] = c @ Mint[:len(c)]
    return out


def gauss_poly_moments(a, kmax):
    """central moments E[u^k] of u = a1 g + a2 He2 + a3 He3, vectorised over rows of a."""
    Mfull = upper_moments(-np.inf, 3 * kmax + 1)
    T = np.stack([-a[:, 1], a[:, 0] - 3 * a[:, 2], a[:, 1], a[:, 2]], 1)
    res = []
    Tr = np.ones((len(a), 1))
    for k in range(1, kmax + 1):
        new = np.zeros((len(a), Tr.shape[1] + 3))
        for j in range(4):
            new[:, j:j + Tr.shape[1]] += Tr * T[:, j:j + 1]
        Tr = new
        res.append(Tr @ Mfull[:Tr.shape[1]])
    return res  # E u, E u^2, ...


def fleishman(g1, g2, iters=30):
    """cubic Hermite transport with unit variance and standardized cumulants (g1, g2)."""
    a = np.stack([1 - g1 ** 2 / 36, g1 / 6, g2 / 24 - g1 ** 2 / 18], 1)

    def F(a):
        e1, e2, e3, e4 = gauss_poly_moments(a, 4)
        return np.stack([e2 - 1, e3 - g1, e4 - 3 * e2 ** 2 - g2], 1)

    for _ in range(iters):
        f = F(a)
        if np.max(np.abs(f)) < 1e-12:
            break
        J = np.zeros((len(a), 3, 3))
        for k in range(3):
            da = np.zeros(3); da[k] = 1e-7
            J[:, :, k] = (F(a + da) - f) / 1e-7
        step = np.linalg.solve(J + 1e-12 * np.eye(3), f[:, :, None])[:, :, 0]
        a = a - np.clip(step, -0.2, 0.2)
    a[:, 0] = np.abs(a[:, 0])
    return a


def mehler(fa, fb, R, d0=1):
    """sum_{d>=d0} fa(d) fb(d) R^d / d!  (fa: (n,D) profile rows, fb: (n,D)), entrywise matrix."""
    out = np.zeros_like(R)
    Rp = np.ones_like(R) if d0 == 0 else R ** d0
    for d in range(d0, min(fa.shape[1], fb.shape[1])):
        out += np.outer(fa[:, d], fb[:, d]) * Rp / FACT[d]
        Rp = Rp * R
    return out


def layer_step(m, s, a, R, W, cfg=None):
    """one copula step: returns (mean of a), and the next state (m', s', a', R'), plus diagnostics."""
    cfg = cfg or {}
    n = len(m)
    pr = profiles(m, s, a, rmax=4, dmax=K)
    h, F2, F3, F4 = pr  # profiles of F, F^2, F^3, F^4
    mu = h[:, 0]
    # centred powers' profiles
    A2 = F2 - 2 * mu[:, None] * h + (mu ** 2)[:, None] * np.eye(1, K + 1, 0)
    A3 = F3 - 3 * mu[:, None] * F2 + 3 * (mu ** 2)[:, None] * h - (mu ** 3)[:, None] * np.eye(1, K + 1, 0)
    var = A2[:, 0]
    k3a = A3[:, 0]
    A4_0 = F4[:, 0] - 4 * mu * F3[:, 0] + 6 * mu ** 2 * F2[:, 0] - 3 * mu ** 4
    k4a = A4_0 - 3 * var ** 2
    R0 = R.copy(); np.fill_diagonal(R0, 0.0)
    # covariance
    Ca = mehler(h, h, R0); Ca[np.diag_indices(n)] = var
    mz = mu @ W
    Cz = W.T @ Ca @ W
    vz = np.diag(Cz).copy()
    W2, W3, W4 = W ** 2, W ** 3, W ** 4
    terms = {}
    # ---- third cumulant
    terms['3:{3}'] = k3a @ W3
    K21 = mehler(A2, h, R0)                         # kappa(a_a,a_a,a_b), a != b (diag 0 since R0 diag 0 -> d>=1 terms vanish)
    terms['3:{2,1}'] = 3 * np.sum(W2 * (K21 @ W), 0)
    X = {p: (R0 ** p) @ (W * h[:, p:p + 1]) / FACT[p] for p in range(1, PQ + 1)}
    t111 = np.zeros(W.shape[1])
    for p in range(1, PQ + 1):
        for q in range(1, PQ + 1):
            if p + q > K:
                continue
            Z = (R0 ** (p + q)) @ (W2 * (h[:, p] * h[:, q])[:, None]) / (FACT[p] * FACT[q])  # a = c terms
            t111 += np.sum(W * h[:, p + q][:, None] * (X[p] * X[q] - Z), 0)
    terms['3:{1,1,1}path'] = 3 * t111
    # ---- fourth cumulant
    terms['4:{4}'] = k4a @ W4
    K22 = mehler(A2, A2, R0) - 2 * mehler(h, h, R0) ** 2
    terms['4:{2,2}'] = 3 * np.sum(W2 * (K22 @ W2), 0)
    A3p = A3.copy()
    K31 = mehler(A3p, h, R0) - 3 * var[:, None] * mehler(h, h, R0)
    terms['4:{3,1}'] = 4 * np.sum(W3 * (K31 @ W), 0)
    t211 = np.zeros(W.shape[1])
    for p in range(1, PQ + 1):
        for q in range(1, PQ + 1):
            if p + q > K:
                continue
            G = A2[:, p + q] - 2 * h[:, p] * h[:, q]
            Zbc = (R0 ** (p + q)) @ (W2 * (h[:, p] * h[:, q])[:, None]) / (FACT[p] * FACT[q])
            t211 += np.sum(W2 * G[:, None] * (X[p] * X[q] - Zbc), 0)
            # path centred at b with the paired vertex a at one end
            Y = (R0 ** p) @ (W2 * A2[:, p:p + 1]) / FACT[p]
            t211 += 2 * np.sum(W * h[:, p + q][:, None] * Y * X[q], 0)
    terms['4:{2,1,1}'] = 6 * t211
    k3z = sum(v for k, v in terms.items() if k.startswith('3:'))
    k4z = sum(v for k, v in terms.items() if k.startswith('4:'))
    if cfg.get('gauss_marg'):
        k3z = 0 * k3z; k4z = 0 * k4z
    # next state
    sz = np.sqrt(vz)
    g1 = k3z / sz ** 3
    g2 = k4z / sz ** 4
    g1 = np.clip(g1, -1.5, 1.5); g2 = np.clip(g2, -1.0, 4.0)
    an = fleishman(g1, g2)
    t = np.stack([sz * an[:, 0], 2 * sz * an[:, 1], 6 * sz * an[:, 2]], 1)
    Rn = latent_corr(Cz, t)
    return mu, (mz, sz, an, Rn), dict(terms=terms, k3=k3z, k4=k4z, vz=vz, Cz=Cz)


def latent_corr(C, t, iters=8):
    T11 = np.outer(t[:, 0], t[:, 0]); T22 = np.outer(t[:, 1], t[:, 1]) / 2; T33 = np.outer(t[:, 2], t[:, 2]) / 6
    r = np.clip(C / T11, -0.999, 0.999)
    for _ in range(iters):
        f = T11 * r + T22 * r ** 2 + T33 * r ** 3 - C
        fp = T11 + 2 * T22 * r + 3 * T33 * r ** 2
        r = np.clip(r - f / fp, -0.999, 0.999)
    np.fill_diagonal(r, 1.0)
    return r


def estimate(W, cfg=None, return_diag=False):
    """W: (L, n, n) in x @ W convention. returns (L, n) means of a_l."""
    L, n, _ = W.shape
    C1 = W[0].T @ W[0]
    s = np.sqrt(np.diag(C1)); R = C1 / np.outer(s, s)
    m = np.zeros(n); a = np.tile([1.0, 0.0, 0.0], (n, 1))
    means, diags = [], []
    for l in range(L):
        if l < L - 1:
            mu, (m, s, a, R), dg = layer_step(m, s, a, R, W[l + 1].astype(float), cfg)
            diags.append(dg)
        else:
            mu = profiles(m, s, a, rmax=1, dmax=0)[0][:, 0]
        means.append(mu)
    return (np.array(means), diags) if return_diag else np.array(means)
