"""Sanity checks for the layered-quiver C*-algebra statements in ../conditional-arrow-algebra.md.

Run:  python3 graph_algebra_checks.py          (fast checks)
      python3 graph_algebra_checks.py --full   (also the two rank computations, a few minutes)
Needs numpy only.  Recorded output (seed 0) is tabulated in Section 9 of the note.


Conventions (Raeburn): an edge e runs from s(e) to r(e); s_e^* s_e = p_{s(e)},
s_e s_e^* <= p_{r(e)}.  A path mu = mu_1 ... mu_n has s(mu_i) = r(mu_{i+1}),
so mu_n is traversed first; s(mu) = s(mu_n) is where it starts, r(mu) = r(mu_1)
where it ends.  The Toeplitz family acts on l^2(E^*) by Q_v h_mu = [r(mu)=v] h_mu
and T_e h_mu = h_{e mu} if s(e) = r(mu) (append e at the head).
"""
import sys, itertools, numpy as np
FULL = "--full" in sys.argv
rng = np.random.default_rng(0)

# layered quiver: faces per layer, arrows from layer l to l+1 (with multiplicity allowed)
layers = [3, 4, 3, 2]          # number of faces per layer, layer 0 = input, last = output
faces = [(l, i) for l, n in enumerate(layers) for i in range(n)]
edges = []
for l in range(len(layers) - 1):
    for i in range(layers[l]):
        for j in range(layers[l + 1]):
            m = rng.integers(0, 3)   # multiplicity 0,1,2
            for k in range(m):
                edges.append(((l, i), (l + 1, j), k))   # (source, range, index)
# make sure every non-input face receives at least one arrow and every non-output face emits one
for l in range(1, len(layers)):
    for j in range(layers[l]):
        if not any(e[1] == (l, j) for e in edges):
            edges.append(((l - 1, 0), (l, j), 9))
for l in range(len(layers) - 1):
    for i in range(layers[l]):
        if not any(e[0] == (l, i) for e in edges):
            edges.append(((l, i), (l + 1, 0), 9))

# all finite paths, represented as tuples of edges (mu_1,...,mu_n) with s(mu_i)=r(mu_{i+1});
# vertices are paths of length 0.
def s(e): return e[0]
def r(e): return e[1]
paths = [(v,) for v in faces]            # length-0 paths encoded as (vertex,)
def path_s(p): return p[0] if len(p) == 1 and p[0] in faces else s(p[-1])
def path_r(p): return p[0] if len(p) == 1 and p[0] in faces else r(p[0])
frontier = [(e,) for e in edges]
while frontier:
    paths += frontier
    new = []
    for p in frontier:
        for e in edges:
            if s(e) == path_r(p):
                new.append((e,) + p)
    frontier = new
index = {p: n for n, p in enumerate(paths)}
N = len(paths)
def basis(p):
    v = np.zeros(N); v[index[p]] = 1.0; return v

Q = {v: np.diag([1.0 if path_r(p) == v else 0.0 for p in paths]) for v in faces}
T = {}
for e in edges:
    M = np.zeros((N, N))
    for p in paths:
        if s(e) == path_r(p):
            q = (e,) + p if not (len(p) == 1 and p[0] in faces) else (e,)
            M[index[q], index[p]] = 1.0
    T[e] = M

# Toeplitz-Cuntz-Krieger relations
for e in edges:
    assert np.allclose(T[e].T @ T[e], Q[s(e)])
for v in faces:
    S = sum(T[e] @ T[e].T for e in edges if r(e) == v) if any(r(e) == v for e in edges) else 0 * Q[v]
    assert np.all(np.linalg.eigvalsh(Q[v] - S) > -1e-9)
print("Toeplitz-Cuntz-Krieger relations hold; number of finite paths N =", N)

# generated *-algebra: span of T_mu T_nu^* with s(mu)=s(nu); compute its dimension
def Tpath(p):
    if len(p) == 1 and p[0] in faces:
        return Q[p[0]]
    M = np.eye(N)
    for e in p:
        M = M @ T[e]
    return M
gens = []
for mu in paths:
    for nu in paths:
        if path_s(mu) == path_s(nu):
            gens.append((Tpath(mu) @ Tpath(nu).T).ravel())
G = np.array(gens)
rank_T = np.linalg.matrix_rank(G, tol=1e-8) if FULL else None
n_w = {w: sum(1 for p in paths if path_s(p) == w) for w in faces}
print("dim of Toeplitz algebra =", rank_T, " predicted sum_w n_w^2 =", sum(n * n for n in n_w.values()))

# Cuntz-Krieger quotient: kill the ideal generated by p_v - sum_{r(e)=v} s_e s_e^* for non-sources.
# Equivalent to restricting to paths whose start s(mu) is a source (layer 0).
sources = [v for v in faces if not any(r(e) == v for e in edges)]
keep = [n for n, p in enumerate(paths) if path_s(p) in sources]
gensCK = []
for mu in paths:
    for nu in paths:
        if path_s(mu) == path_s(nu) and path_s(mu) in sources:
            A = (Tpath(mu) @ Tpath(nu).T)[np.ix_(keep, keep)]
            gensCK.append(A.ravel())
rank_CK = np.linalg.matrix_rank(np.array(gensCK), tol=1e-8) if FULL else None
print("dim of Cuntz-Krieger quotient (restricted) =", rank_CK,
      " predicted sum over sources of N(s0)^2 =", sum(n_w[v] ** 2 for v in sources))
# and the kernel of the CK relations contains exactly the trivial paths at non-sources
for v in faces:
    if v in sources: continue
    D = Q[v] - sum(T[e] @ T[e].T for e in edges if r(e) == v)
    assert np.allclose(D, np.diag([1.0 if p == (v,) else 0.0 for p in paths]))
print("p_v - sum s_e s_e^* is the projection onto the trivial path at v (history-free v), as claimed")

# vertex projection restricted to complete histories = number of complete histories ending there
L = len(layers) - 1
complete = [p for p in paths if path_s(p) in sources and path_r(p)[0] == L]
h = {t: sum(1 for p in complete if path_r(p) == t) for t in faces if t[0] == L}
Nc = {v: sum(1 for p in complete if path_s(p) == v) for v in sources}
print("complete histories:", len(complete), " by endpoint:", h, " by origin:", Nc)

# KMS check on the complete-history corner with a generalised gauge action F on edges
F = {e: rng.normal() for e in edges}
def Fpath(p): return sum(F[e] for e in p) if not (len(p) == 1 and p[0] in faces) else 0.0
beta = 0.7
idx = {p: n for n, p in enumerate(complete)}
Hdiag = np.array([Fpath(p) for p in complete])
# origin-block algebra on complete histories: matrix units e_{mu nu} with same origin
# Gibbs state per block; check KMS condition phi(ab) = phi(b alpha_{i beta}(a)) for matrix units
def alpha_ib(mu, nu):   # alpha_{i beta}(e_{mu nu}) = e^{-beta (F(mu)-F(nu))} e_{mu nu}
    return np.exp(-beta * (Fpath(mu) - Fpath(nu)))
w = {v: rng.random() for v in sources}; Z = {v: sum(np.exp(-beta * Fpath(p)) for p in complete if path_s(p) == v) for v in sources}
tot = sum(w.values())
def phi(mu, nu):        # state on matrix units
    if mu != nu: return 0.0
    v = path_s(mu)
    return w[v] / tot * np.exp(-beta * Fpath(mu)) / Z[v]
maxerr = 0.0
for a in complete:
    for b in complete:
        if path_s(a) != path_s(b): continue
        for c in complete:
            if path_s(c) != path_s(a): continue
            # ab = e_{a b} e_{b c} = e_{a c};  b alpha(a): e_{b c} e_{a b}-> needs c == a
            lhs = phi(a, c)
            rhs = phi(b, b) * alpha_ib(a, b) if c == a else 0.0
            # general: phi(e_{ab} e_{bc}) = phi(e_{ac}); phi(e_{bc} alpha_{ib}(e_{ab})) = [c==a] alpha_ib(a,b) phi(e_{bb})
            maxerr = max(maxerr, abs(lhs - rhs))
print("KMS condition for the origin-block Gibbs measure: max violation =", maxerr)

# sufficiency / coboundary check.
# Statistic T(mu) is sufficient for the Gibbs family P_beta(mu) ~ exp(-beta F(mu)) over complete histories
# iff F(mu) is a function of T(mu)  (classical factorisation criterion, all beta).
def sufficient(F, T):
    byT = {}
    for p in complete:
        byT.setdefault(T(p), set()).add(round(sum(F[e] for e in p), 9))
    return all(len(v) == 1 for v in byT.values())
endpoint = lambda p: path_r(p)
origin_endpoint = lambda p: (path_s(p), path_r(p))
V = {v: rng.normal() for v in faces}
Fcob = {e: V[r(e)] - V[s(e)] for e in edges}                      # coboundary, arbitrary on layer 0
V0 = {v: (0.0 if v[0] == 0 else rng.normal()) for v in faces}
Fcob0 = {e: V0[r(e)] - V0[s(e)] for e in edges}                   # coboundary with potential 0 on the input layer
for name, FF in [("random F", F), ("coboundary F=dV", Fcob), ("coboundary with V=0 on layer 0", Fcob0)]:
    print(f"{name:34s} endpoint sufficient: {sufficient(FF, endpoint)!s:5s}  (origin,endpoint) sufficient: {sufficient(FF, origin_endpoint)}")

# propagation number of the depth-truncated operator system E_k = span{s_mu s_nu^* : |mu|,|nu| <= k, s(mu)=s(nu)}
# inside the Toeplitz algebra T(Lambda), where the spanning elements s_mu s_nu^* form a BASIS (their number equals
# sum_w N(w)^2 = dim T(Lambda), checked above with --full).  Products of basis elements are basis elements or 0, so
# the span of n-fold products is spanned by the index pairs reachable by the product rule.  Claim (note, Sec. 7.1):
# prop(E_k) = 2*ceil(L/k) - 1 in T(Lambda); in the Cuntz-Krieger quotient it is at most this.
import math
def edges_of(p): return () if (len(p) == 1 and p[0] in faces) else p
def start_of(p): return path_s(p)
def canon(ed, start):
    return (start,) if len(ed) == 0 else ed
def product(mu, nu, al, be):
    """(s_mu s_nu^*)(s_al s_be^*) by the product rule; returns the index pair or None if the product is 0."""
    nu_e, al_e = edges_of(nu), edges_of(al)
    if len(nu_e) == 0 and len(al_e) == 0:
        return (mu, be) if start_of(nu) == start_of(al) else None
    if len(nu_e) == 0:                       # s_nu = p_v: p_v s_al = s_al iff r(al) = v, so al = nu al' with al' = al
        return (canon(edges_of(mu) + al_e, start_of(al)), be) if path_r(al) == start_of(nu) else None
    if len(al_e) == 0:                       # s_al = p_w: s_nu^* p_w = s_nu^* iff r(nu) = w, so nu = al nu' with nu' = nu
        return (mu, canon(edges_of(be) + nu_e, start_of(nu))) if path_r(nu) == start_of(al) else None
    if al_e[:len(nu_e)] == nu_e:             # al = nu al'
        return (canon(edges_of(mu) + al_e[len(nu_e):], start_of(al)), be)
    if nu_e[:len(al_e)] == al_e:             # nu = al nu'
        return (mu, canon(edges_of(be) + nu_e[len(al_e):], start_of(nu)))
    return None
span_pairs = {(mu, nu) for mu in paths for nu in paths if path_s(mu) == path_s(nu)}
assert len(span_pairs) == sum(n * n for n in n_w.values())
Lmax = max(len(edges_of(p)) for p in paths)
for k in range(1, Lmax + 1):
    Ek = {(mu, nu) for (mu, nu) in span_pairs if len(edges_of(mu)) <= k and len(edges_of(nu)) <= k}
    reach, n = set(Ek), 1
    while reach != span_pairs and n < 4 * Lmax:
        new = set(reach)
        for (mu, nu) in reach:
            for (al, be) in Ek:
                pr = product(mu, nu, al, be)
                if pr is not None:
                    assert pr in span_pairs, pr
                    new.add(pr)
        reach, n = new, n + 1
    print(f"k={k}: prop(E_k) in T(Lambda) = {n}   predicted 2*ceil(L/k)-1 = {2 * math.ceil(Lmax / k) - 1}   (L = {Lmax})")
