"""WhestBench Phase 2 estimator: finite-resolution cumulant closure.

Deterministic Gaussian-closure propagation of the layer means and covariances, corrected at every
layer by the leading non-Gaussian (third/fourth cumulant) structure of the pre-activations, which is
resolved at two levels:

  * exactly for the most recent source layer (the third-cumulant tensor generated by the ReLU
    kinks of the previous layer, in factorised diagram form, contracted with the current weights);
  * at coarse resolution for the inherited part, using a small Monte-Carlo sample: the third
    cumulants of the pre-activations are aligned with their standardised means (a per-layer linear
    fit), the excess kurtosis is a per-layer constant, and the two-point third cumulants
    kappa(z_a, z_a, z_b) are rank one along the propagated mean direction.

All arithmetic is float32 flopscope; the sample count is chosen from the budget so the whole call
stays at the 10 % compute floor.
"""
import math

import numpy as np

try:
    import flopscope as flops
    import flopscope.numpy as fnp
except Exception:  # pragma: no cover
    flops = None
    fnp = None

try:
    from whestbench.sdk import BaseEstimator
except Exception:  # pragma: no cover
    class BaseEstimator:
        def setup(self, context):
            return None

F32 = np.float32
INV_SQRT2PI = 0.3989422804014327


def _phi(xp, t):
    return xp.exp(t * t * F32(-0.5)) * F32(INV_SQRT2PI)


def _Phi(xp, t):
    """Standard normal CDF in float32 (Abramowitz-Stegun 7.1.26, |err| < 3.1e-7)."""
    x = xp.abs(t) * F32(0.7071067811865476)
    u = F32(1.0) / (F32(1.0) + F32(0.3275911) * x)
    poly = ((((F32(1.061405429) * u + F32(-1.453152027)) * u + F32(1.421413741)) * u
             + F32(-0.284496736)) * u + F32(0.254829592)) * u
    half = poly * xp.exp(-(x * x)) * F32(0.5)
    return xp.where(t >= 0, F32(1.0) - half, half)


class FiniteResolutionCumulantEstimator(BaseEstimator):
    MC_FRACTION = 0.045     # share of the budget spent on Monte-Carlo samples
    MC_MAX = 2400
    T_ACT = 2.75            # |mu/sigma| threshold for the per-neuron third-cumulant contraction
    HERMITE_ORDER = 8
    USE_SOURCE = True       # exact previous-layer source (third cumulants + two-point slice)
    USE_MC = True
    USE_KERNEL = True       # shipped reduced memory kernel for the omitted source layers

    # Reduced self-energy of the omitted source sector, in the rank-one basis  a_l * t * sigma^3,
    # with the layer's mean excess kurtosis alongside.  Fitted offline on public networks 0-7 of the
    # mini shard (24 fits, three Monte-Carlo seeds each); see notes/whestbench/diagnostics/shipped.py.
    # Indexed by relative depth so a different (width, depth) shape cannot fall off the end.
    # Each entry is (a, g4, c2p): the diagonal self-energy coefficient on t*sigma^3, the layer's mean
    # excess kurtosis, and the two-point self-energy coefficient on sigma^3 along the propagated mean
    # direction.  The two-point tail's mean-direction coefficient is 97-99% explained by sigma^3 alone
    # (measured with oracle inputs), and like the diagonal one its across-network spread is at or below
    # the spread from changing the Monte-Carlo seed, so it is a function of relative depth.
    KERNEL = (
        (0.00094, 0.00715, 0.00396), (0.00783, 0.01340, 0.07819), (0.01134, 0.01947, 0.14538),
        (0.01406, 0.02302, 0.22329), (0.01658, 0.02679, 0.30105), (0.01853, 0.03065, 0.38174),
        (0.02040, 0.03478, 0.45643), (0.02217, 0.03824, 0.55252), (0.02331, 0.04162, 0.63162),
        (0.02464, 0.04615, 0.70963), (0.02555, 0.04940, 0.80605), (0.02684, 0.05096, 0.92641),
        (0.02781, 0.05280, 1.00444), (0.02838, 0.05462, 1.09326), (0.02940, 0.05873, 1.18779),
    )
    W2P = 0.75              # weight on the shipped two-point coefficient against the sampled one

    def kernel_at(self, l, depth):
        """Schedule entry for layer l of a depth-`depth` network, by relative depth."""
        tbl = self.KERNEL
        if depth <= 2:
            return tbl[0]
        f = (l - 1) / float(depth - 2)
        i = int(round(f * (len(tbl) - 1)))
        return tbl[min(max(i, 0), len(tbl) - 1)]

    def __init__(self, xp=None, numpy_mode=False):
        self.xp = xp if xp is not None else fnp
        self.numpy_mode = numpy_mode or (self.xp is np)

    # ------------------------------------------------------------------ helpers
    def symm(self, C):
        if self.numpy_mode:
            return C
        return flops.as_symmetric(C, symmetry=(0, 1))

    def sandwich(self, W, S):
        xp = self.xp
        if self.numpy_mode:
            return (W.T @ S) @ W
        try:
            return xp.einsum('ji,jk,kl->il', W, self.symm(S), W)
        except Exception:
            return xp.matmul(xp.matmul(xp.transpose(W), S), W)

    def gram(self, W):
        xp = self.xp
        if self.numpy_mode:
            return W.T @ W
        try:
            return xp.einsum('ji,jk->ik', W, W)
        except Exception:
            return xp.matmul(xp.transpose(W), W)

    def hermite_coeffs(self, t, ph, Ph, kmax):
        x = -t
        ds = [Ph, ph]
        he_prev, he = F32(1.0), x
        for k in range(3, kmax + 1):
            ds.append(ph * he)
            he_prev, he = he, x * he - F32(k - 2) * he_prev
        return ds[:kmax]

    @staticmethod
    def lstsq2(xp, x1, x2, y):
        """least squares y ~ a x1 + b x2 over the neurons (2x2 normal equations)."""
        a11 = (x1 * x1).sum(); a12 = (x1 * x2).sum(); a22 = (x2 * x2).sum()
        b1 = (x1 * y).sum(); b2 = (x2 * y).sum()
        det = a11 * a22 - a12 * a12
        ca = (a22 * b1 - a12 * b2) / det
        cb = (a11 * b2 - a12 * b1) / det
        return ca, cb

    # --------------------------------------------------------------------- main
    def predict(self, mlp, budget):
        xp = self.xp
        n, L = mlp.width, mlp.depth
        Ws = [xp.asarray(w) for w in mlp.weights]
        per_sample = 2 * n * n * L + 40 * n * L + 16 * n
        N = int(min(self.MC_MAX, (self.MC_FRACTION * budget) // per_sample)) if self.USE_MC else 0
        if N < 64:
            N = 0
        # ---------------- Monte-Carlo pass -------------------------------------------------------
        Zs = None
        if N > 0:
            rng = xp.random.default_rng(int(mlp.seed) & 0xFFFFFFFF)
            h = rng.standard_normal((N, n), dtype=xp.float32)
            Zs = []
            for l in range(L):
                z = xp.matmul(h, Ws[l])
                Zs.append(z)
                if l < L - 1:
                    h = xp.maximum(z, F32(0.0))
        invN = F32(1.0 / N) if N > 0 else F32(0.0)
        outs = []
        # ---------------- layer 0: exact ---------------------------------------------------------
        W0 = Ws[0]
        G = self.gram(W0)
        s2 = xp.diag(G)
        s = xp.sqrt(s2)
        m = s * F32(INV_SQRT2PI)
        so = xp.outer(s, s)
        rho = xp.clip(G / so, F32(-1.0), F32(1.0))
        C = so * ((xp.sqrt(F32(1.0) - rho * rho) + rho * (F32(math.pi) - xp.arccos(rho))) * F32(1.0 / (2 * math.pi))) - xp.outer(m, m)
        C = C - xp.diag(xp.diag(C)) + xp.diag(s2 * F32(0.5 - 1.0 / (2 * math.pi)))
        Msrc = G * F32(0.5)
        Msrc = Msrc - xp.diag(xp.diag(Msrc))
        src = (Msrc, F32(INV_SQRT2PI) / s, m, s2 * s * F32(2 * INV_SQRT2PI - 1.5 * INV_SQRT2PI + 2 * INV_SQRT2PI ** 3))
        outs.append(m)
        Sig = C
        # ---------------- layers 1 .. L-1 ---------------------------------------------------------
        for l in range(1, L):
            Wl = Ws[l]
            mu = xp.matmul(m, Wl)
            Sz = self.sandwich(Wl, Sig)
            sz2 = xp.diag(Sz)
            sz = xp.sqrt(sz2)
            t = mu / sz
            ph = _phi(xp, t)
            Ph = _Phi(xp, t)
            Psi = mu * Ph + sz * ph
            m2 = (mu * mu + sz2) * Ph + mu * sz * ph
            s3 = sz2 * sz
            s4 = sz2 * sz2
            k3 = None
            K21 = None
            # ---- exact previous-layer source: per-neuron k3 (active neurons) and two-point slice ----
            if self.USE_SOURCE:
                Ms, ps, qs, k3hs = src
                act = np.nonzero(np.asarray(xp.abs(t) < F32(self.T_ACT)))[0]
                U = Wl
                Nt = xp.matmul(xp.transpose(Ms), U)                       # (n, n): (M^T w_b)_beta
                UN = U * Nt
                A = (ps[:, None] * F32(3.0)) * UN * Nt + (qs[:, None] * F32(3.0)) * UN * U + k3hs[:, None] * (U * U * U)
                k3 = A.sum(axis=0)
                X1 = (UN * F32(2.0)) * ps[:, None] + (U * U) * qs[:, None]           # -> [X1]^T Nt
                X2 = (Nt * Nt) * ps[:, None] + (UN * F32(2.0)) * qs[:, None] + (U * U) * k3hs[:, None]   # -> [X2]^T U
                if act.size > 0 and act.size < n:
                    X1a = X1[:, act]; X2a = X2[:, act]
                    Ka = xp.matmul(xp.transpose(X1a), Nt) + xp.matmul(xp.transpose(X2a), U)   # (n_act, n)
                    # rows of inactive neurons are zero: place the active block by a row gather (4 FLOPs/elem)
                    order = np.concatenate([act, np.setdiff1d(np.arange(n), act)])
                    inv = np.empty(n, dtype=np.int64); inv[order] = np.arange(n)
                    full = xp.concatenate([Ka, xp.zeros((n - act.size, n), dtype=xp.float32)], axis=0)
                    K21 = full[inv, :]
                else:
                    K21 = xp.matmul(xp.transpose(X1), Nt) + xp.matmul(xp.transpose(X2), U)
                K21 = K21 - xp.diag(xp.diag(K21))
            # ---- Monte-Carlo resolution of the inherited non-Gaussianity -------------------------
            k4 = None
            if Zs is not None:
                z = Zs[l]
                a = z.sum(axis=0) * invN
                zc = z - a[None, :]
                zc2 = zc * zc
                v = zc2.sum(axis=0) * invN
                k3s = (zc2 * zc).sum(axis=0) * invN
                k4s = (zc2 * zc2).sum(axis=0) * invN - F32(3.0) * v * v
                # aligned third cumulant: (k3s - k3_source)/s^3 ~ a t + b
                base = k3 if k3 is not None else F32(0.0)
                if self.USE_KERNEL:
                    ak, g4k, c2pk = self.kernel_at(l, L)
                    k3 = base + (t * s3) * F32(ak)
                else:
                    r = (k3s - base) / s3
                    ca, cb = self.lstsq2(xp, t, xp.ones(n, dtype=xp.float32), r)
                    k3 = base + (ca * t + cb) * s3
                # shrink towards the per-neuron sample value with the estimated signal/noise weight
                resid = k3s - k3
                noise = (s3 * s3).sum() * F32(6.0 / max(N, 1))
                sig = (resid * resid).sum() - noise
                w = xp.maximum(sig, F32(0.0)) / (xp.maximum(sig, F32(0.0)) + noise)
                k3 = k3 + w * resid
                # excess kurtosis: per-layer constant, shipped or measured
                g4 = F32(g4k) if self.USE_KERNEL else (k4s / s4).sum() * F32(1.0 / n)
                k4 = g4 * s4
                # inherited two-point cumulants along the mean direction
                muh = mu / xp.sqrt((mu * mu).sum())
                Aproj = xp.matmul(zc, muh)
                u = xp.matmul(xp.transpose(zc2), Aproj) * invN
                if K21 is not None:
                    u = u - xp.matmul(K21, muh)
                if self.USE_KERNEL:
                    # blend the sampled mean-direction coefficient with the shipped analytic one
                    u = (s3 * F32(c2pk)) * F32(self.W2P) + u * F32(1.0 - self.W2P)
                K21 = xp.outer(u, muh) if K21 is None else K21 + xp.outer(u, muh)
                K21 = K21 - xp.diag(xp.diag(K21))
            # ---- Edgeworth readout -------------------------------------------------------------
            m_next = Psi
            dE2 = None
            if k3 is not None:
                t2 = t * t
                he2 = t2 - F32(1.0)
                he4 = (t2 - F32(6.0)) * t2 + F32(3.0)
                tph = t * ph
                k3sq = k3 * k3
                dE1 = -k3 * tph / (sz2 * F32(6.0)) + k3sq * he4 * ph / (s4 * sz * F32(72.0))
                dE2 = k3 * ph / (sz * F32(3.0)) + k3sq * (F32(3.0) * t - t * t2) * ph / (s4 * F32(36.0))
                if k4 is not None:
                    dE1 = dE1 + k4 * he2 * ph / (s3 * F32(24.0))
                    dE2 = dE2 - k4 * tph / (sz2 * F32(12.0))
                m_next = Psi + dE1
            # ---- covariance closure of h_{l+1} ----------------------------------------------------
            so = xp.outer(sz, sz)
            rho = Sz / so
            ds = self.hermite_coeffs(t, ph, Ph, self.HERMITE_ORDER)
            rk = rho
            C = None
            fact = 1.0
            for k in range(1, self.HERMITE_ORDER + 1):
                fact *= k
                dk = ds[k - 1]
                term = rk * xp.outer(dk, dk) if k == 1 else rk * xp.outer(dk, dk * F32(1.0 / fact))
                C = term if C is None else C + term
                if k < self.HERMITE_ORDER:
                    rk = rk * rho
            C = C * so
            if K21 is not None:
                F2 = ph / sz
                C = C + (K21 * xp.outer(F2, Ph) + xp.transpose(K21) * xp.outer(Ph, F2)) * F32(0.5)
            var = m2 - Psi * Psi if dE2 is None else (m2 + dE2) - m_next * m_next
            C = C - xp.diag(xp.diag(C)) + xp.diag(var)
            # ---- source state for the next layer -----------------------------------------------
            if self.USE_SOURCE:
                Msrc = Sz * Ph[:, None]
                Msrc = Msrc - xp.diag(xp.diag(Msrc))
                m3 = mu * m2 + F32(2.0) * sz2 * Psi
                src = (Msrc, ph / sz, F32(2.0) * Psi * (F32(1.0) - Ph), m3 - F32(3.0) * m2 * Psi + F32(2.0) * Psi * Psi * Psi)
            m = m_next
            Sig = C
            outs.append(m)
        return xp.stack(outs)


Estimator = FiniteResolutionCumulantEstimator
